### ISSUE TITLE
Error sending transaction Not found

### ISSUE THREAD

**Issue by prateushsharma** [Constellation-Labs/metagraph-examples#25]
Did everything still facing the error in runing the script
prateush@prateush-Nitro-AN515-56:~/metagraph-examples/examples/voting-poll/scripts$ node send_data_transaction.js 
Transaction body: {"value":{"VoteInPoll":{"pollId":":new poll","address":"DAG0AdGMqmBhcLQeeSCRMpemyVUpKmPLJAszForV","option":"hi"}},"proofs":[{"id":"5fbb374439c9d8a15533cc4d3ffda732a52cea2c7690e54f3b4c12fe9b92304b29ca491b49e6ae65868003dbf0ceb830d2fc691b4543356aa4c199eb0026ffa0","signature":"3045022100f09448536593c9f726b87fdfaa685e307e718c3713b4f324a9c4160943eeb15302204df76744d33e94b5286a79f923859197b6e6a38627d85f952814c959708f107a"}]}
Error sending transaction Not found
prateush@prateush-Nitro-AN515-56:~/metagraph-examples/examples/voting-poll/scripts$

**Comment by scasplte2** [comment]
Hi @prateushsharma, looking at that script, it seems like the relevant portion is
```javascript
 try {
        console.log( `Transaction body: ${JSON.stringify( body )}` );
        const response = await axios.post( `${metagraphL1DataUrl}/data`, body );
        console.log( `Response: ${JSON.stringify( response.data )}` );
    } catch( e ) {
        console.log( 'Error sending transaction', e.message );
    }
```

where the line that is failing is specifically `const response = await axios.post( ${metagraphL1DataUrl}/data, body );` so it seems like the HTTP client is failing to locate the server and therefore reporting the error `Not found`

Have you updated the URL variables to target the server locations displayed by Euclid in this portion of the script?
```javascript
const sendDataTransaction = async () => {
    const globalL0Url = ':your_global_l0_node_url';
    const metagraphL1DataUrl = ':your_metagraph_l1_data_url';

    await sendDataTransactionsUsingUrls( globalL0Url, metagraphL1DataUrl );
};
```

**Comment by AlexBrandes** [comment]
Closing for now because it looks like it was solved - feel free to open a new issue if the problem persists.
